default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pracasta_development
  username: wisnuadhimukti
  password:

test:
  <<: *default
  database: pracasta_test

production:
  <<: *default
  database: pracasta_production
  username: pracasta
  password: <%= ENV['PRACASTA_DATABASE_PASSWORD'] %>
